resources:
- name: task-repository
  type: git
  source:
    uri: https://github.com/imanuelr/helloCIWorld.git

- name: app-repository
  type: git
  source:
    uri: https://github.com/imanuelr/helloCIWorld.git

- name: resource-share
  type: git
  source:
    branch: master
    uri: {{ci-artifacts-url}}
    private_key: {{ci-artifacts-key}}


jobs:
- name: build-gradle
  public: true
  plan:
  - get: app-repository
    trigger: true
  - get: task-repository
  - get: resource-share
  - task: Build gradle project
    file: task-repository/concourseCI/tasks/task_build_gradle.yaml
  - put: resource-share
    params: {repository: updated-gist}

- name: integration-tests
  public: true
  plan:
  - get: resource-share
    passed: [build-gradle]
    trigger: true
  - get: task-repository
  - task: Run integration tests
    file: task-repository/concourseCI/tasks/task_integration_tests.yaml

- name: deploy-to-test-env
  public: true
  serial: true
  plan:
  - get: resource-share
    passed: [integration-tests]
  - get: task-repository
  - task: Deploy build to test environment
    file: task-repository/concourseCI/tasks/task_deploy_to_testenv.yaml