---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: app-repository

run:
  path: app-repository/concourseCI/tasks/build-artifact.sh