---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ismailchaida/java-git}

inputs:
  - name: app-repository
  - name: resource-share

outputs:
  - name: updated-gist

run:
  path: sh
  args: ["app-repository/concourseCI/tasks/build-artifact.sh"]